#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
# xrandr --output Virtual1 --mode 1680x1050 &
nitrogen --restore &
~/.config/polybar/launch.sh &
picom &

# Workspaces
bspc monitor -d I II III IV V

# Other settings
bspc config border_width         2
bspc config window_gap           8
bspc config split_ratio          0.5


